import Button from "@/components/Button";
import Head from "next/head";
import Link from "next/link";
import { auth } from "@/libs/firebase";
import { useEffect, useState } from "react";

export default function Home() {
    const [loggedin, setLoggedin] = useState<boolean>(false);
    const [loading, setLoading] = useState<boolean>(true);
    useEffect(() => {
        auth.onAuthStateChanged((user) => {
            if (user) {
                setLoggedin(true);
            }
            setLoading(false);
        });
    });
    return (
        <>
            <Head>
                <title>AI Writter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-screen justify-center items-center">
                <div className="space-y-4">
                    <h1 className="animate-text bg-gradient-to-r from-teal-500 via-purple-500 to-orange-500 bg-clip-text text-transparent text-6xl font-black">
                        Create, Summarize Text Now! <br />
                        With the help of AI
                    </h1>
                    <div className="flex flex-col gap-4 items-center">
                        {loggedin ? (
                            <Link href={`/dashboard`}>
                                <Button>Dashboard</Button>
                            </Link>
                        ) : (
                            <div className="flex gap-4">
                                <Link href={`/signup`}>
                                    <Button>Signup</Button>
                                </Link>
                                <Link href={`/login`}>
                                    <Button>Login</Button>
                                </Link>
                            </div>
                        )}
                    </div>
                </div>
            </main>
        </>
    );
}
